class AuditCertificateService
  def initialize(signature_request)
    @signature_request = signature_request
    @document = signature_request.document
  end

  def generate!
    doc = HexaPDF::Document.new
    page = doc.pages.add([0, 0, 612, 792]) # US Letter
    canvas = page.canvas

    y = 740

    # Header
    canvas.font("Helvetica", size: 24, variant: :bold)
    canvas.fill_color(0.15, 0.15, 0.5)
    canvas.text("Pact", at: [50, y])
    y -= 15

    canvas.font("Helvetica", size: 10)
    canvas.fill_color(0.4, 0.4, 0.4)
    canvas.text("Audit Certificate", at: [50, y])
    y -= 8

    # Divider
    canvas.stroke_color(0.2, 0.2, 0.6)
    canvas.line_width(2)
    canvas.line(50, y, 562, y)
    canvas.stroke
    y -= 30

    # Document info section
    canvas.font("Helvetica", size: 12, variant: :bold)
    canvas.fill_color(0, 0, 0)
    canvas.text("Document Information", at: [50, y])
    y -= 20

    info_lines = [
      ["Document Name", @document.name],
      ["Signature Request ID", @signature_request.id.to_s],
      ["Document Hash (SHA-256)", @document.file_hash.presence || "N/A"],
      ["Created", @signature_request.created_at.strftime("%B %d, %Y at %l:%M:%S %p %Z")]
    ]

    info_lines.each do |label, value|
      canvas.font("Helvetica", size: 9, variant: :bold)
      canvas.fill_color(0.3, 0.3, 0.3)
      canvas.text("#{label}:", at: [60, y])
      canvas.font("Helvetica", size: 9)
      canvas.fill_color(0, 0, 0)
      canvas.text(value.to_s, at: [220, y])
      y -= 16
    end

    y -= 15

    # Signer info
    canvas.font("Helvetica", size: 12, variant: :bold)
    canvas.fill_color(0, 0, 0)
    canvas.text("Signer Information", at: [50, y])
    y -= 20

    signer_lines = [
      ["Name", @signature_request.signer_display_name],
      ["Email", @signature_request.signer_email],
      ["IP Address", @signature_request.ip_address.presence || "N/A"],
      ["User Agent", truncate_text(@signature_request.user_agent.presence || "N/A", 80)],
      ["Signed At", @signature_request.signed_at&.strftime("%B %d, %Y at %l:%M:%S %p %Z") || "N/A"]
    ]

    signer_lines.each do |label, value|
      canvas.font("Helvetica", size: 9, variant: :bold)
      canvas.fill_color(0.3, 0.3, 0.3)
      canvas.text("#{label}:", at: [60, y])
      canvas.font("Helvetica", size: 9)
      canvas.fill_color(0, 0, 0)
      canvas.text(value.to_s, at: [220, y])
      y -= 16
    end

    y -= 15

    # Field completions
    if @signature_request.uses_multi_field?
      canvas.font("Helvetica", size: 12, variant: :bold)
      canvas.fill_color(0, 0, 0)
      canvas.text("Field Completion Details", at: [50, y])
      y -= 20

      @signature_request.signature_fields.includes(:completion).order(:position).each do |field|
        next unless field.completed?

        canvas.font("Helvetica", size: 9, variant: :bold)
        canvas.fill_color(0.15, 0.15, 0.5)
        canvas.text("#{field.label} (#{field.field_type})", at: [60, y])
        y -= 14

        completion = field.completion
        completion_lines = [
          ["Page", field.page_number.to_s],
          ["Completed At", completion.completed_at&.strftime("%B %d, %Y at %l:%M:%S %p %Z") || "N/A"],
          ["IP Address", completion.ip_address.presence || "N/A"]
        ]

        completion_lines.each do |label, value|
          canvas.font("Helvetica", size: 8)
          canvas.fill_color(0.4, 0.4, 0.4)
          canvas.text("#{label}: #{value}", at: [80, y])
          y -= 12
        end

        y -= 8

        # Add new page if running low on space
        if y < 80
          page = doc.pages.add([0, 0, 612, 792])
          canvas = page.canvas
          y = 740
        end
      end
    end

    # Footer
    y = [y - 30, 80].min
    canvas.stroke_color(0.7, 0.7, 0.7)
    canvas.line_width(0.5)
    canvas.line(50, y, 562, y)
    canvas.stroke
    y -= 15

    canvas.font("Helvetica", size: 8)
    canvas.fill_color(0.5, 0.5, 0.5)
    canvas.text("This audit certificate was automatically generated by Pact.", at: [50, y])
    y -= 12
    canvas.text("Generated on #{Time.current.strftime('%B %d, %Y at %l:%M:%S %p %Z')}", at: [50, y])

    output = StringIO.new
    doc.write(output)
    output.string
  rescue => e
    Rails.logger.error "Audit certificate generation failed: #{e.message}"
    Rails.logger.error e.backtrace.join("\n")
    nil
  end

  private

  def truncate_text(text, max_length)
    return text if text.length <= max_length
    text[0...max_length] + "..."
  end
end
